swagger: "2.0"
info:
  version: "1.0.0"
  title: "Transaction Management API"
  description: "An API for managing user transactions"
host: localhost:3001
basePath: /app/v1
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /transactions/{id}:
    parameters:
      - in: path
        name: id
        description: ID of the transaction to retrieve/modify/delete
        required: true
        type: integer
    get:
      security:
        - Bearer: []
      summary: Get a transaction
      description: "This route returns a specific transaction for the user."
      parameters:
        - in: header
          name: Authorization
          description: "Attach Bearer JWT token"
          required: true
          type: string
        - in: path
          name: id
          description: "ID of the transaction to retrieve"
          required: true
          type: integer
      responses:
        '200':
          description: "Success in retrieving the transaction"
          schema:
            $ref: '#/definitions/allTransactions'
        '400':
          description: "Invalid Fields"
        '500':
          description: "Internal Server Error"
    put:
      security:
        - Bearer: []
      summary: Update a category
      description: "This route allows modifying a category."
      parameters:
        - in: header
          name: Authorization
          description: "Attach Bearer JWT token"
          required: true
          type: string
        - in: path
          name: id
          description: "ID of the transaction to modify"
          required: true
          type: integer
        - in: body
          name: body
          description: "New transaction data"
          required: true
          schema:
            $ref: '#/definitions/objectTransaction'
      responses:
        '200':
          description: "Success in modifying the category"
        '400':
          description: "Invalid Fields"
        '500':
          description: "Internal Server Error"
    delete:
      security:
        - Bearer: []
      summary: Delete a transaction
      description: "This route allows deleting a specific transaction for the user."
      parameters:
        - in: header
          name: Authorization
          description: "Attach Bearer JWT token"
          required: true
          type: string
        - in: path
          name: id
          description: "ID of the transaction to delete"
          required: true
          type: integer
      responses:
        '200':
          description: "Success in deleting the transaction"
        '400':
          description: "Invalid Fields"
        '500':
          description: "Internal Server Error"
  /transactions:
    get:
      security:
        - Bearer: []
      summary: Get all transactions
      description: "This route returns all transactions for the user."
      parameters:
        - in: header
          name: Authorization
          description: "Attach Bearer JWT token"
          required: true
          type: string
      responses:
        '200':
          description: "Success in retrieving the transactions"
          schema:
            $ref: '#/definitions/allTransactions'
        '400':
          description: "Invalid Fields"
        '500':
          description: "Internal Server Error"
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  allTransactions:
    properties:
      date:
        type: string
        format: date-time
        example: "2022-05-09T10:30:00.000Z"
      description:
        type: string
        example: "Purchased a new phone"
      amount:
        type: number
        example: 25.99
      balance:
        type: number
        example: 153.20
      type:
        type: string
        example: "Electronic"
      category:
        type: string
        example: "Shopping"
      note:
        type: string
        example: "Purchased a new phone"
  objectTransaction:
    properties:
      description:
        type: string
        example: "Purchased bird food"
